#!/bin/bash
# Author:
#   Lauri Koivuniemi
#   www.github.com/koivuniemi
#
# ================================================================================
#   MIT License
#
#   Copyright (c) 2024 Lauri Koivuniemi
#
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.
# ================================================================================


if [[ $1 == "-h" || $1 == "--help" ]]; then
    BNAME=$(basename -- $0)
    echo "Usage: $BNAME [index|name] [max|brightness]"
    echo "Examples:"
    echo -e "\t$BNAME       | list devices | (index) (device_name) (brightness) (max_brightness)"
    echo -e "\t$BNAME 0     | list index 0 device info"
    echo -e "\t$BNAME 1 3   | index 1 device changed to brightness 3"
    echo -e "\t$BNAME kbd m | device with 'kbd' in its name changed to max_brightness"
    exit
fi


DIRECTORIES=$(sudo find /sys/devices -name *backlight)
DIRS=()
for dir in $DIRECTORIES; do
    if [[ -f $dir/britghtness || -f $dir/max_brightness ]]; then
        DIRS+=($dir)
    fi
done


if [[ -z $DIRS ]]; then
    echo "no devices with modifiable brightness"
    exit
elif [[ -z $1 ]]; then
    str=''
    for i in ${!DIRS[@]}; do
        str+="$i $(basename -- ${DIRS[i]}) $(cat ${DIRS[i]}/brightness) $(cat ${DIRS[i]}/max_brightness)\n"
    done
    echo -e $str | column -t
    exit
fi

dir=''
if [[ $1 =~ ^[0-9]+$ ]]; then
    dir=${DIRS[$1]}
else
    for file in ${DIRS[@]}; do
        if [[ $(basename -- $file) =~ $1 ]]; then
            dir=$file
            break
        fi
    done
fi
if [[ -z $dir ]]; then
    echo "no matching option: $1"
    exit
fi
if [[ -z $2 ]]; then
    echo "$(basename -- $dir) $(cat $dir/brightness) $(cat $dir/max_brightness)"
    exit
fi


MAX_BRIGHTNESS=$(cat $dir/max_brightness)
brightness=''
if [[ $2 =~ ^[0-9]+$ && $2 -ge 0 ]]; then
    brightness=$2
    if [[ $brightness > $MAX_BRIGHTNESS ]]; then
        brightness=$MAX_BRIGHTNESS
    fi
elif [[ $2 == "m" || $2 == "max" ]]; then
    brightness=$MAX_BRIGHTNESS
else
    echo "incorrect parameter: $2"
    exit
fi

sudo su -c "echo $brightness > $dir/brightness"
