#!/bin/bash
# Author:
#   Lauri Koivuniemi
#   www.github.com/koivuniemi
#
# ================================================================================
#   MIT License
#
#   Copyright (c) 2024 Lauri Koivuniemi
#
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.
# ================================================================================


flag_h=false
flag_v=false

commands=()
for arg in $@; do
    if [[ $arg == "-h" || $arg == "--help" ]]; then
        flag_h=true
    elif [[ $arg == "-v" ]]; then
        flag_v=true
    else
        commands+=($arg)
    fi
done
ID=${commands[0]}
VAL=${commands[1]}


if $flag_h; then
    BNAME=$(basename -- $0)
    echo "Usage: $BNAME [OPTION] [index|name] [max|brightness]"
    echo "Options:"
    echo -e "\t-h --help\t| Displays this information"
    echo -e "\t-v\t\t| Verbose"
    echo "Examples:"
    echo -e "\t$BNAME\t\t| List devices | (index) (device_name) (brightness) (max_brightness)"
    echo -e "\t0  asus::kbd_backlight  0      3"
    echo -e "\t1  intel_backlight      10000  19200"
    echo
    echo -e "\t$BNAME 0\t| List index 0 device info"
    echo -e "\tasus::kbd_backlight 0 3"
    echo
    echo -e "\t$BNAME 1 3\t| Index 1 device changed to brightness 3"
    echo -e "\t$BNAME kbd m\t| Device with 'kbd' in its name changed to max_brightness"
    exit
fi


DIRS=($(dirname $(sudo find /sys/devices -type f -name "brightness")))


if [[ -z $DIRS ]]; then
    echo "No devices with modifiable brightness"
    exit
fi
if [[ -z $ID ]]; then
    str=''
    if $flag_v; then
        for i in ${!DIRS[@]}; do
            str+="$i ${DIRS[i]} $(cat ${DIRS[i]}/brightness) $(cat ${DIRS[i]}/max_brightness)\n"
        done
    else
        for i in ${!DIRS[@]}; do
            str+="$i $(basename -- ${DIRS[i]}) $(cat ${DIRS[i]}/brightness) $(cat ${DIRS[i]}/max_brightness)\n"
        done
    fi
    echo -e $str | column -t
    exit
fi


dir=''
if [[ $ID =~ ^[0-9]+$ ]]; then
    dir=${DIRS[$ID]}
else
    for file in ${DIRS[@]}; do
        if [[ $(basename -- $file) =~ $ID ]]; then
            dir=$file
            break
        fi
    done
fi


if [[ -z $dir ]]; then
    echo "No matching option: $1"
    exit
fi
if [[ -z $VAL ]]; then
    if $flag_v; then
        echo "$dir $(cat $dir/brightness) $(cat $dir/max_brightness)"
    else
        echo "$(basename -- $dir) $(cat $dir/brightness) $(cat $dir/max_brightness)"
    fi
    exit
fi


MAX_BRIGHTNESS=$(cat $dir/max_brightness)
if [[ $VAL =~ ^[0-9]+$ && $VAL -ge 0 ]]; then
    if [[ $bness -gt $MAX_BRIGHTNESS ]]; then
        VAL=$MAX_BRIGHTNESS
    fi
elif [[ $VAL == "m" || $VAL == "max" ]]; then
    VAL=$MAX_BRIGHTNESS
else
    echo "Incorrect second parameter: $VAL"
    exit
fi

if $flag_v; then
    echo -e "sudo su -c \"echo $VAL > $dir/brightness\""
fi
sudo su -c "echo $VAL > $dir/brightness"
