#!/bin/bash
# Author:
#   Lauri Koivuniemi
#   www.github.com/koivuniemi
#
# ================================================================================
#   MIT License
#
#   Copyright (c) 2024 Lauri Koivuniemi
#
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#
#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.
#
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.
# ================================================================================


flag_a=false
flag_h=false
flag_v=false
commands=()
for arg in $@; do
    case $arg in
        -a)
            flag_a=true;;
        -h | --help)
            flag_h=true;;
        -v)
            flag_v=true;;
        *)
            commands+=($arg);;
    esac
done
id=${commands[0]}
val=${commands[1]}


if $flag_h; then
    BNAME=$(basename -- $0)
    echo "Usage: $BNAME [OPTION] [index|name] [max|brightness]"
    echo "Options:"
    echo -e "\t-a\t\t| Additional devices (default is only backlight devices)"
    echo -e "\t-h --help\t| Displays this information"
    echo -e "\t-v\t\t| Verbose"
    echo "Examples:"
    echo -e "\t$BNAME\t\t| List devices | (index) (device) (brightness) (max_brightness)"
    echo -e "\t$BNAME 0\t| List index 0 device info"
    echo -e "\t$BNAME 1 3\t| Index 1 device changed to brightness 3"
    echo -e "\t$BNAME kbd m\t| Device with 'kbd' in its name changed to max_brightness"
    exit
fi


DIRS=''
if $flag_a; then
    DIRS=($(dirname $(sudo find /sys/devices -type f -name "brightness")))
else
    DIRS=($(sudo find /sys/devices -type d -name "*light" -exec test -e '{}'/brightness \; -print))
fi
if [[ -z $DIRS ]]; then
    echo "No devices with modifiable brightness"
    exit
fi
if [[ -z $id ]]; then
    str=''
    if $flag_v; then
        for i in ${!DIRS[@]}; do
            str+="$i ${DIRS[i]} $(cat ${DIRS[i]}/brightness) $(cat ${DIRS[i]}/max_brightness)\n"
        done
    else
        for i in ${!DIRS[@]}; do
            str+="$i $(basename -- ${DIRS[i]}) $(cat ${DIRS[i]}/brightness) $(cat ${DIRS[i]}/max_brightness)\n"
        done
    fi
    echo -e $str | column -t
    exit
fi


dir=''
if [[ $id =~ ^[0-9]+$ ]]; then
    dir=${DIRS[$id]}
else
    for file in ${DIRS[@]}; do
        if [[ $(basename -- $file) =~ $id ]]; then
            dir=$file
            break
        fi
    done
fi
if [[ -z $dir ]]; then
    echo "No matching option: $1"
    exit
fi
if [[ -z $val ]]; then
    if $flag_v; then
        echo "$dir $(cat $dir/brightness) $(cat $dir/max_brightness)"
    else
        echo "$(basename -- $dir) $(cat $dir/brightness) $(cat $dir/max_brightness)"
    fi
    exit
fi


MAX_BRIGHTNESS=$(cat $dir/max_brightness)
if [[ $val =~ ^[0-9]+$ && $val -ge 0 ]]; then
    if [[ $val -gt $MAX_BRIGHTNESS ]]; then
        val=$MAX_BRIGHTNESS
    fi
elif [[ $val == "m" || $val == "max" ]]; then
    val=$MAX_BRIGHTNESS
else
    echo "Incorrect second parameter: $val"
    exit
fi
if $flag_v; then
    echo -e "sudo su -c \"echo $val > $dir/brightness\""
fi
sudo su -c "echo $val > $dir/brightness"
